// <auto-generated />
using System;
using MagazinCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MagazinCore.Migrations
{
    [DbContext(typeof(MagazinCoreContext))]
    [Migration("20201119070538_AdaugareTabelaProdus")]
    partial class AdaugareTabelaProdus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MagazinCore.Models.Produs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Acciz")
                        .HasColumnType("real");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<string>("Culoare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Denumire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndReducere")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Reducere")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartReducere")
                        .HasColumnType("datetime2");

                    b.Property<float>("Tva")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Produs");
                });
#pragma warning restore 612, 618
        }
    }
}
